import type { Application, Job, JobAISummary } from "@/types/job";
import type { DemoSeniorProfile } from "@/types/user";

const baseDate = "2026-05-16T00:00:00.000Z";

export const mockJobs: Job[] = [
  {
    id: "job_001",
    source: "mock",
    sourceName: "시니어클럽 예시 데이터",
    externalId: "mock-welfare-guide",
    employerId: null,
    title: "복지관 안내 도우미",
    organization: "햇살복지관",
    region: "서울 중구",
    workLocation: "서울 중구 햇살복지관",
    workTime: "오전 9시부터 낮 12시까지, 주 3일",
    pay: "월 76만원 내외",
    eligibility: "60세 이상, 서울 중구 거주자 우대",
    description: "복지관에 오신 분들에게 위치를 안내하고 프로그램실 정리를 돕는 일입니다.",
    applicationMethod: "복지관에 전화 후 신분증을 가지고 방문",
    requiredDocuments: "신분증, 주민등록등본",
    startDate: "2026-05-20T00:00:00.000Z",
    endDate: "2026-06-10T00:00:00.000Z",
    rawData: null,
    status: "active",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "job_002",
    source: "mock",
    sourceName: "공공근로 예시 데이터",
    externalId: "mock-park-care",
    employerId: null,
    title: "동네 공원 환경 정리",
    organization: "지역 공원관리소",
    region: "경기 고양시",
    workLocation: "고양시 동네 공원",
    workTime: "오전 8시부터 11시까지, 주 4일",
    pay: "시급 1만원 수준",
    eligibility: "건강하게 가벼운 야외 활동이 가능한 분",
    description: "공원 산책로 주변의 작은 쓰레기를 줍고 벤치 주변을 정리하는 일입니다.",
    applicationMethod: "주민센터 일자리 담당자에게 문의",
    requiredDocuments: "신분증, 통장 사본",
    startDate: "2026-05-18T00:00:00.000Z",
    endDate: "2026-06-03T00:00:00.000Z",
    rawData: null,
    status: "active",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "job_003",
    source: "mock",
    sourceName: "상점 채용 예시 데이터",
    externalId: "mock-store-helper",
    employerId: null,
    title: "동네 마트 진열 보조",
    organization: "우리동네마트",
    region: "부산 해운대구",
    workLocation: "부산 해운대구 우동",
    workTime: "오후 2시부터 5시까지, 주 3일",
    pay: "시급 1만 1천원",
    eligibility: "가벼운 물건을 옮길 수 있는 분",
    description: "진열대 물건을 정리하고 손님이 물건 위치를 물으면 알려주는 일입니다.",
    applicationMethod: "매장 전화 후 면담",
    requiredDocuments: "신분증",
    startDate: "2026-05-16T00:00:00.000Z",
    endDate: "2026-05-31T00:00:00.000Z",
    rawData: null,
    status: "active",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
];

export const mockSummaries: JobAISummary[] = [
  {
    id: "summary_job_001",
    jobId: "job_001",
    title: "복지관 안내 도우미",
    summary: "복지관에 오신 분들에게 장소를 알려드리고, 프로그램실을 간단히 정리하는 일입니다.",
    eligibility: "60세 이상이고 서울 중구에 사시면 신청 가능성이 높습니다.",
    workCondition: "오전 3시간, 주 3일 정도 일합니다.",
    applicationGuide: [
      "햇살복지관에 전화합니다.",
      "모집이 아직 진행 중인지 물어봅니다.",
      "신분증과 주민등록등본을 준비합니다.",
      "복지관에 방문해 신청서를 작성합니다.",
    ],
    caution: "오래 서 있는 시간이 있을 수 있으니 몸 상태를 먼저 확인하세요.",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "summary_job_002",
    jobId: "job_002",
    title: "동네 공원 환경 정리",
    summary: "동네 공원에서 산책로와 벤치 주변을 깨끗하게 정리하는 일입니다.",
    eligibility: "가벼운 야외 활동이 가능하고 해당 지역에 사시면 신청할 수 있습니다.",
    workCondition: "오전 3시간, 주 4일 정도 일합니다.",
    applicationGuide: [
      "사는 곳 주민센터에 전화합니다.",
      "공공근로 또는 노인 일자리 담당자를 찾습니다.",
      "신분증과 통장 사본을 준비합니다.",
      "방문해서 신청서를 작성합니다.",
    ],
    caution: "야외에서 하는 일이므로 더운 날이나 비 오는 날 근무 조건을 확인하세요.",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
];

export const mockApplications: Application[] = [
  {
    id: "app_001",
    jobId: "job_001",
    userId: "user_mock_001",
    applicantName: "김영자",
    phone: "010-1234-5678",
    resumeSummary: "복지관 자원봉사 경험 2년. 오전 근무를 희망합니다.",
    status: "submitted",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "app_002",
    jobId: "job_003",
    userId: "user_mock_002",
    applicantName: "박성호",
    phone: "010-2222-3333",
    resumeSummary: "마트 근무 경험이 있고 가까운 거리 근무를 원합니다.",
    status: "reviewed",
    createdAt: baseDate,
    updatedAt: baseDate,
  },
];

export const mockSeniorProfiles: DemoSeniorProfile[] = [
  {
    id: "senior_001",
    userId: "user_senior_001",
    name: "김영자",
    phone: "010-1234-5678",
    ageRange: "60대",
    region: "서울 중구",
    previousWork: "사람을 안내하거나 손님을 응대한 경험",
    preferredTime: "오전 짧은 시간",
    healthLimit: "허리나 무릎이 불편함",
    preferredJobType: "안내 도우미",
    consentToEmployerMatching: true,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "senior_002",
    userId: "user_senior_002",
    name: "박성호",
    phone: "010-2222-3333",
    ageRange: "50대",
    region: "부산 해운대구",
    previousWork: "청소, 정리, 물건 관리 경험",
    preferredTime: "오후 짧은 시간",
    healthLimit: "특별히 아픈 곳 없음",
    preferredJobType: "정리 보조",
    consentToEmployerMatching: true,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "senior_003",
    userId: "user_senior_003",
    name: "이정순",
    phone: null,
    ageRange: "60대",
    region: "경기 고양시",
    previousWork: "청소, 정리, 물건 관리 경험",
    preferredTime: "오전 짧은 시간",
    healthLimit: "손이나 어깨가 불편하거나 무거운 물건을 피해야 함",
    preferredJobType: "가벼운 정리",
    consentToEmployerMatching: true,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
];
